# Generated by Django 2.1.5 on 2019-01-24 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190123_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='tutorial_name',
            new_name='tutorial_title',
        ),
    ]
