# Generated by Django 2.1.5 on 2019-01-24 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190123_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 18, 20, 31, 283242), verbose_name='date published'),
        ),
    ]
