# Generated by Django 2.1.5 on 2019-02-21 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190221_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 13, 58, 57, 228047), verbose_name='date published'),
        ),
    ]
