# Generated by Django 2.1.5 on 2019-02-21 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190221_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialcategory',
            old_name='tutorial_slug',
            new_name='category_slug',
        ),
        migrations.RenameField(
            model_name='tutorialcategory',
            old_name='tutorial_summary',
            new_name='category_summary',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 14, 4, 22, 420565), verbose_name='date published'),
        ),
    ]
