# Generated by Django 2.1.5 on 2019-02-21 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190221_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialseries',
            old_name='tutorial_summary',
            new_name='series_summary',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 14, 9, 59, 797392), verbose_name='date published'),
        ),
    ]
